version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      wordpress:
        patterns:
          - "@wordpress/*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      phpstan:
        patterns:
          - "phpstan/*"
        update-types:
          - "minor"
          - "patch"
      phpunit:
        patterns:
          - "phpunit/*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"